#!/usr/bin/env python3
"""
Generate plugins/DirtyTalk/DirtyTalkIRs.h from the "Small Speaker IR Pack"
(Jim / HippieLoveTurbo.com -- free, credited in IR_CREDITS.md).

Each source WAV (32-bit float, stereo, 44.1 kHz, ~4 s) is:
  1. summed to mono,
  2. trimmed of leading silence (acquisition pre-delay),
  3. truncated to IR_LEN taps (small-speaker colour lives in the first ~90 ms),
  4. tail-faded (half-cosine) to avoid a hard cut,
  5. normalised to unit L2 energy so every IR sits at a comparable loudness.

The result is emitted as a compact C header of float arrays at 44.1 kHz; the
plugin resamples to the host rate at load time.

Usage:
    python3 tools/gen_irs.py "/path/to/Small Speaker IR Pack - Hippie Love Turbo"
"""
import sys, os, struct, glob, re, math, array

IR_LEN      = 4096          # taps kept per IR (~93 ms @ 44.1 kHz)
IR_SR       = 44100
TAIL_FADE   = 512           # half-cosine fade over the last N taps
ONSET_DB    = -40.0         # onset detected at this level below peak
ONSET_BACK  = 16            # keep this many taps before the detected onset


def load_wav_mono(path):
    d = open(path, 'rb').read()
    assert d[:4] == b'RIFF' and d[8:12] == b'WAVE', "not a WAV: " + path
    i, ch, sr, bits, fmt, data = 12, 0, 0, 0, 0, b''
    while i < len(d):
        cid = d[i:i+4]
        sz  = struct.unpack('<I', d[i+4:i+8])[0]
        body = d[i+8:i+8+sz]
        if cid == b'fmt ':
            fmt, ch, sr, _br, _ba, bits = struct.unpack('<HHIIHH', body[:16])
        elif cid == b'data':
            data = body
        i += 8 + sz + (sz & 1)
    assert fmt == 3 and bits == 32, "expected 32-bit float WAV (%s)" % path
    a = array.array('f'); a.frombytes(data)
    if ch == 1:
        mono = list(a)
    else:
        mono = [sum(a[k:k+ch]) / ch for k in range(0, len(a), ch)]
    return sr, mono


def process(mono):
    peak = max((abs(x) for x in mono), default=0.0)
    if peak <= 0.0:
        return [0.0] * IR_LEN
    thr = peak * (10.0 ** (ONSET_DB / 20.0))
    onset = next((k for k, x in enumerate(mono) if abs(x) > thr), 0)
    start = max(0, onset - ONSET_BACK)
    seg = mono[start:start + IR_LEN]
    seg += [0.0] * (IR_LEN - len(seg))
    # half-cosine tail fade
    for n in range(TAIL_FADE):
        w = 0.5 * (1.0 + math.cos(math.pi * n / TAIL_FADE))
        seg[IR_LEN - TAIL_FADE + n] *= w
    # L2 normalise
    energy = math.sqrt(sum(x * x for x in seg))
    if energy > 0.0:
        seg = [x / energy for x in seg]
    return seg


def natural_key(path):
    m = re.search(r'(\d+)', os.path.basename(path))
    return int(m.group(1)) if m else 0


def main():
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    src = sys.argv[1]
    wavs = sorted(glob.glob(os.path.join(src, '*.wav')), key=natural_key)
    if not wavs:
        print("no WAV files in", src); sys.exit(1)

    irs, names = [], []
    for w in wavs:
        sr, mono = load_wav_mono(w)
        assert sr == IR_SR, "expected %d Hz, got %d (%s)" % (IR_SR, sr, w)
        irs.append(process(mono))
        m = re.search(r'(\d+)', os.path.basename(w))
        names.append("Speaker %02d" % (int(m.group(1)) if m else len(names) + 1))

    out = os.path.join(os.path.dirname(__file__), '..', 'plugins', 'DirtyTalk', 'DirtyTalkIRs.h')
    out = os.path.normpath(out)
    with open(out, 'w') as f:
        f.write("/*\n")
        f.write(" * Dirty Talk - embedded small-speaker impulse responses.\n")
        f.write(" * GENERATED by tools/gen_irs.py -- do not edit by hand.\n")
        f.write(" *\n")
        f.write(" * Source: \"Small Speaker IR Pack\" by Jim (HippieLoveTurbo.com), free to\n")
        f.write(" * use with attribution (see IR_CREDITS.md). Mono, %d taps, %d Hz,\n" % (IR_LEN, IR_SR))
        f.write(" * L2-normalised. The plugin resamples to the host rate at load time.\n")
        f.write(" */\n")
        f.write("#ifndef DIRTY_TALK_IRS_H\n#define DIRTY_TALK_IRS_H\n\n")
        f.write("namespace dirtytalk_irs {\n\n")
        f.write("static const int kNumIRs = %d;\n" % len(irs))
        f.write("static const int kIRSampleRate = %d;\n" % IR_SR)
        f.write("static const int kIRLength = %d;\n\n" % IR_LEN)
        f.write("static const char* const kIRNames[%d] = {\n    " % len(irs))
        f.write(", ".join('"%s"' % n for n in names))
        f.write("\n};\n\n")
        f.write("static const float kIRData[%d][%d] = {\n" % (len(irs), IR_LEN))
        for j, ir in enumerate(irs):
            f.write("{\n")
            for n in range(0, IR_LEN, 8):
                row = ir[n:n+8]
                f.write("  " + ",".join("%.8ff" % v for v in row) + ",\n")
            f.write("},\n")
        f.write("};\n\n")
        f.write("} // namespace dirtytalk_irs\n\n")
        f.write("#endif // DIRTY_TALK_IRS_H\n")
    print("wrote", out, "(%d IRs, %d taps each)" % (len(irs), IR_LEN))


if __name__ == '__main__':
    main()
